name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-redis:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3

      - run: corepack enable
      - run: yarn set version 3.6.4
      
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Setup and run tests
        run: |
          docker-compose up -d
          yarn
          yarn test
          docker-compose down
